version: "3.8"

services:
  ftp-server:
    build:
      dockerfile: Dockerfile
      context: ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      # Mount for uploaded data
      - "./ftp-mounts/data/:/home/prototype/"
      # Mount SSL keys for TLS
      - "./ftp-mounts/ssl/:/etc/ssl/private/"
    environment:
      USERS: "prototype|mypass"
      ADDRESS: "localhost"

  uploader:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      ftp-server:
        condition: service_started
