version: "3.8"

services:
  ftp-server:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      # Mount for uploaded data
      - "./ftp-mounts/data/:/home/prototype/"
      # Mount SSL keys for TLS
      - "./ftp-mounts/ssl/:/etc/ssl/private/"
    environment:
      USERS: "prototype|mypass"
      ADDRESS: "localhost"
      TLS_CERT: "/etc/ssl/private/localhost.crt"
      TLS_KEY: "/etc/ssl/private/localhost.key"


  uploader:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      ftp-server:
        condition: service_started
